version: "3.8"
services:
  app:
    build: .
    ports:
      - 3001:3001
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      WAIT_HOSTS: db:5432
  db: 
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data: